### ISSUE TITLE
Need a simple tutorial about modifying the theme color and university logo

### ISSUE THREAD

**Issue by WissenY** [Qilong-Kirov-LIU/Beamer-LaTeX-Themes#2]
Your templates are so beautiful that i want to use it in my university style. So can you simply introduce where and how to modify 
 the theme color and logo?

**Comment by Qilong-Kirov-LIU** [comment]
I forget to add this part. It should be available in README now. Please check the [Make Your Own Theme?](https://github.com/Qilong-Kirov-LIU/Beamer-LaTeX-Themes#make-your-own-theme) section.

Is it clear enough? Your feedback will be highly appreciated 🤝

**Comment by WissenY** [comment]
Thank you very much! I think it is a very detailed and easy-to-implement intro for beginning users like me 😁
