### ISSUE TITLE
Where to put the class option [aspectratio=43]? 

### ISSUE THREAD

**Issue by JC6123** [Qilong-Kirov-LIU/Beamer-LaTeX-Themes#3]
I'd like to change the aspect ratio to 4:3. Using `\documentclass[aspectratio=43]{sintefbeamer}` in `pre.tex` seems not working. Where should I put this option? 

Besides, I guess I should also change the `background.png` to 4:3, right? What else should be modified?

Thanks!

**Comment by Qilong-Kirov-LIU** [comment]
Thanks for your feedback. These templates are secondary creations of [SINTEF Presentation](https://www.overleaf.com/latex/templates/sintef-presentation/jhbhdffczpnx) template. The original author force beamer to use 16:9 aspect ratio in the 28-th line of `beamerthemesintef.sty`:
```
\geometry{paperwidth=16cm,paperheight=9cm}
```
As you can see, the absolute size of the slides are hard-coded. To avoid wrecking the proportion of the elements presented on the slides, it's recommended to change it in this way:
```
\geometry{paperwidth=16cm,paperheight=12cm}
```

**Comment by JC6123** [comment]
Seems it works. Thanks!
